---
env:
  node: true
  es6: true

rules:
  semi: 2
  comma-dangle: 2
  no-undef: 2
  no-extra-semi: 2
  no-eval: 2
  no-underscore-dangle: 0
  eqeqeq:
    - 2
    - smart
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  no-console: 2
  no-plusplus: 2
  space-unary-ops:
    - 2
    - words: true
      nonwords: false
  no-unused-vars: 2
  no-trailing-spaces:
    - 2
    - skipBlankLines: true
  no-unreachable:
    - 2
  no-alert: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  no-var: 1
  quotes:
    - 2
    - "single"

parserOptions:
  sourceType: module
